### ISSUE TITLE
Implementar componente de barra de seek do vídeo

### ISSUE THREAD

**Issue by PietroCarrara** [PietroCarrara/submat#4]
Usando o store do vídeo (#3), uma barra deve mostrar o progresso do filme. Se o usuário arrastar a bolinha dela, ela deve mudar o momento do vídeo.

O bootstrap já tem [ranges](https://getbootstrap.com/docs/5.3/components/progress/) prontos, é uma boa dar uma lida lá.

![scrollable](https://user-images.githubusercontent.com/26305940/223000188-21324ed3-a216-48e8-a032-a5a48f697dc2.jpg)

**Comment by Lucas-Bonorino** [comment]
Problema de drag funcionar apenas quando usa-se o dev mode no browser

**Comment by PietroCarrara** [comment]
Refatorado por 499db315aedee297adb1b5d8705f922afacfb512:

- Separar o código da ProgressBar em um componente próprio (`ProgressBar.vue`), e adicioná-lo ao `VideoPlayer.vue`: Isso mantém a lógica dessas partes da UI separadas, e mais fáceis de ler/editar
- `document.getElementByID` é legal, mas o Vue tem uma feature própria pra isso: [os refs](https://vuejs.org/guide/essentials/template-refs.html#template-refs).
